spring:
  application:
    name: service-a

  datasource:
    url: jdbc:postgresql://localhost:5432/service_a
    username: admin
    password: 050912
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080